// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/kanban-store @ cfcbfa930ae2b9577c1929cdaa8d327056510941-dirty
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.
import type { Item as NoteboardItem } from "@kayushkin/noteboard-types";

//////////
// source: activity.go

/**
 * ClockState says what the time following an event does to the card's time
 * limit. It is stored on the event itself rather than derived at read time from
 * the event kind or the column: ladders get re-tuned and columns get
 * re-classified, and a timeline has to keep reporting what was true when the
 * action actually happened.
 */
export type ClockState = string;
/**
 * ClockRunning — the work is ours to do, so the time after this event counts
 * against the card's limit.
 */
export const ClockRunning: ClockState = "running";
/**
 * ClockPaused — someone else has the ball: an unanswered email, a blocked
 * dependency, a held card. Time still elapses. It does not count against the
 * limit.
 */
export const ClockPaused: ClockState = "paused";
/**
 * ClockStopped — the work is over. Nothing accrues after this event, neither
 * elapsed time nor budget.
 */
export const ClockStopped: ClockState = "stopped";
/**
 * EventKind is the action that happened to a card. The set below is what
 * kanban-store records for itself; the kind field is deliberately open so a
 * caller can record an action this service has never heard of. What an unknown
 * kind cannot do is guess its own clock state — see DefaultClockStateForEventKind.
 */
export type EventKind = string;
export const EventCardCreated: EventKind = "card_created";
export const EventCardAttached: EventKind = "card_attached";
export const EventCardDetached: EventKind = "card_detached";
export const EventCardMoved: EventKind = "card_moved";
export const EventCardHeld: EventKind = "card_held";
export const EventCardUnheld: EventKind = "card_unheld";
export const EventCardCompleted: EventKind = "card_completed";
export const EventEmailReceived: EventKind = "email_received";
export const EventAgentDispatched: EventKind = "agent_dispatched";
export const EventAgentFinished: EventKind = "agent_finished";
export const EventNoteAdded: EventKind = "note_added";
export const EventWaitingStarted: EventKind = "waiting_started";
export const EventWaitingEnded: EventKind = "waiting_ended";
/**
 * EventAssigned and EventUnassigned are a principal being put on the card
 * or taken off it. Like a move they have no kind-level clock state (see the
 * map below): who is on the work says nothing about whether the work is
 * runnable, so the event carries whatever state the card was already in.
 */
export const EventAssigned: EventKind = "assigned";
export const EventUnassigned: EventKind = "unassigned";
/**
 * CardEvent is one action on one card at one moment. The time between an event
 * and the next one is attributed to this event's ClockState — that walk is the
 * whole of the time accounting, and it is why there are no running totals stored
 * anywhere to drift out of step with the log.
 * BoardID is empty for actions that are not about a particular board — an email
 * arriving concerns the card wherever it sits. A card's timeline on a board is
 * its board-specific events merged with its card-wide ones.
 */
export interface CardEvent {
  id: string;
  card_id: string;
  board_id?: string;
  kind: EventKind;
  clock_state: ClockState;
  actor?: string;
  summary?: string;
  from_column_id?: string;
  to_column_id?: string;
  note_id?: string;
  /**
   * SupersedesEventID names an earlier event this one replaces. The log stays
   * append-only: the earlier event is never touched, and is read as inactive
   * because this one points at it. At most one event may supersede another.
   * Used by time_logged; see EventTimeLogged.
   */
  supersedes_event_id?: string;
  detail?: unknown;
  occurred_at: string;
  recorded_at: string;
}
/**
 * CreateCardEventRequest records an action from outside kanban-store — an email
 * classifier attaching mail, an agent reporting that it finished, a human noting
 * that a reply went out and the ball is now with the other side.
 */
export interface CreateCardEventRequest {
  kind: EventKind;
  board_id?: string;
  clock_state?: ClockState;
  actor?: string;
  summary?: string;
  /**
   * OccurredAt backdates the event to when the action really happened, which is
   * not always when it is reported: a classifier reads a mailbox on a cadence,
   * so the email arrived before anything here heard about it. Empty means now.
   */
  occurred_at?: string;
  detail?: unknown;
}
/**
 * CardNote is a status update or a summary written onto a card — an email
 * classified and condensed, an agent reporting what it changed, a human leaving
 * context for the next person.
 * It lives here rather than in the noteboard item's body because it is activity,
 * not the card's text: notes accumulate, each one is stamped and attributed, and
 * adding one is an action on the timeline. The body still says what the work is;
 * the notes say what has happened to it.
 */
export interface CardNote {
  id: string;
  card_id: string;
  board_id?: string;
  kind: string;
  /**
   * Visibility says who the note is for: the people working the card, or the
   * requester as well. See NoteVisibility.
   */
  visibility: NoteVisibility;
  body: string;
  actor?: string;
  created_at: string;
}
/**
 * NoteVisibility is who a note is written for. It is a fact about the note,
 * recorded when it is written, and this store shows every note to every caller
 * who can view the card: the people working a ticket need the internal ones
 * most. What it decides is what a requester-facing reader — a portal, a reply
 * sent by mail — may pass on, and that reader asks for `requester` notes only.
 */
export type NoteVisibility = string;
/**
 * NoteVisibilityInternal is for the people working the card and nobody else.
 */
export const NoteVisibilityInternal: NoteVisibility = "internal";
/**
 * NoteVisibilityRequester may be shown to the person who asked.
 */
export const NoteVisibilityRequester: NoteVisibility = "requester";
/**
 * DefaultNoteVisibility is what a note written without one gets, and what every
 * note written before the field existed is. Internal, because the other
 * default would show a requester something by omission.
 */
export const DefaultNoteVisibility = NoteVisibilityInternal;
/**
 * NoteAddedEventDetail is the detail of a note_added event. The event's summary
 * is the note's body, so the timeline carries a note's text; the visibility
 * rides beside it so a requester-facing reader of the timeline can drop the
 * internal ones without fetching each note.
 */
export interface NoteAddedEventDetail {
  visibility: NoteVisibility;
}
export interface CreateCardNoteRequest {
  body: string;
  board_id?: string;
  /**
   * Kind labels what sort of update this is — a free-text label such as
   * "summary" or "status". Empty stores "note".
   */
  kind?: string;
  actor?: string;
  /**
   * Visibility is `internal` or `requester` (GET /api/note-visibilities).
   * Empty stores `internal`: a note is never shown to a requester because
   * its writer left a field out.
   */
  visibility?: NoteVisibility;
  /**
   * ClockState lets a note move the clock, since some updates are exactly the
   * moment the ball changes hands ("replied, waiting on them"). Empty leaves the
   * clock where the note_added default puts it.
   */
  clock_state?: ClockState;
  occurred_at?: string;
}
/**
 * UnsetPriorityValue is the noteboard priority of a card nobody has ranked.
 * noteboard defaults the column to 0 and sorts descending, so 0 is the bottom of
 * the scale and the value 7,904 of this host's items sit at.
 * It is reserved: a board's ladder may not define a level at 0. That keeps
 * "unranked" and "most urgent" from collapsing into one number, which they would
 * if P0 were stored literally as zero.
 */
export const UnsetPriorityValue = 0;
/**
 * BoardPriorityLevel is one rung of a board's ladder: a noteboard priority value,
 * the name the board gives it, and how long work at that rung should take.
 * P0 is the top rung, and the top rung is the one with the HIGHEST PriorityValue
 * — noteboard sorts priority descending and every list view in the stack already
 * depends on that. The P-number is a label on a rung, not the number in the
 * database.
 */
export interface BoardPriorityLevel {
  board_id: string;
  priority_value: number /* int */;
  label: string;
  /**
   * BudgetSeconds is the time limit for work at this rung, measured on the
   * budget clock. Nil means this rung is named but not timed.
   */
  budget_seconds: number | null;
  /**
   * DefaultAutoHoldAtUSD is the spend ceiling a card is GIVEN when it lands on
   * this rung — a starting value written onto the card's noteboard
   * auto_hold_at_usd, which stays editable per card. It is not enforced from
   * here: the scheduler's spend-ceiling-guard reads the card, never the ladder.
   * Nil means this rung suggests no ceiling. Zero is a real default ("stop
   * before spending a cent"), hence the pointer.
   */
  default_auto_hold_at_usd: number | null;
}
/**
 * PriorityLadder is a board's whole ladder, top rung first. An empty ladder means
 * the board ignores priorities: its cards get no rung, no label and no limit.
 */
export interface PriorityLadder {
  board_id: string;
  levels: BoardPriorityLevel[];
}
/**
 * SetPriorityLadderRequest replaces a board's ladder outright. A ladder is one
 * object — rungs are only meaningful relative to each other — so there is no
 * endpoint for editing a single rung.
 */
export interface SetPriorityLadderRequest {
  levels: BoardPriorityLevel[];
}
/**
 * BusinessHours is a board's working week, used to report elapsed time a second
 * way: alongside the plain wall-clock figures, not instead of them.
 * TZID is mandatory and never defaulted, for the same reason noteboard's
 * recurrence rules demand one — an offset is not a zone, and a board whose hours
 * were guessed reports numbers nobody can check.
 */
export interface BusinessHours {
  tzid: string;
  days: string[];
  start: string;
  end: string;
  /**
   * Holidays are dates, in the board's own zone, on which no business time
   * counts however the week is drawn: "2026-12-25". Stored sorted.
   * On a PATCH, absent and empty differ, as they do for the board's other
   * fields: business_hours sent without holidays keeps the stored ones, so a
   * client that edits only the working week cannot wipe them by not knowing
   * they exist; `"holidays":[]` clears them. Clearing the business hours
   * themselves clears these too, since a holiday is a date in their zone.
   */
  holidays?: string[];
}
/**
 * HolidayDateLayout is how a holiday is written: a calendar date with no time
 * and no zone, because the zone is the board's.
 */
export const HolidayDateLayout = "2006-01-02";
/**
 * MaxHolidays bounds the list. Twenty years of a generous calendar fits.
 */
export const MaxHolidays = 500;

//////////
// source: bulk.go

/**
 * BulkCardCommand names one command a bulk request applies to many cards.
 */
export type BulkCardCommand = string;
export const BulkCommandMove: BulkCardCommand = "move";
export const BulkCommandAssign: BulkCardCommand = "assign";
export const BulkCommandUnassign: BulkCardCommand = "unassign";
export const BulkCommandHold: BulkCardCommand = "hold";
export const BulkCommandUnhold: BulkCardCommand = "unhold";
export const BulkCommandAddTags: BulkCardCommand = "add_tags";
export const BulkCommandRemoveTags: BulkCardCommand = "remove_tags";
/**
 * MaxBulkCardCommandCards bounds one bulk request. Each card is a full
 * single-card command with its own checks and its own event, so a request is
 * as slow as its cards are many.
 */
export const MaxBulkCardCommandCards = 200;
/**
 * BulkCardCommandOptions is GET /api/bulk-card-commands.
 */
export interface BulkCardCommandOptions {
  commands: BulkCardCommand[];
  max_cards: number /* int */;
}
/**
 * BulkCardCommandRequest is POST /api/bulk-card-commands: one command, many
 * cards. Only the field its command reads may be set; any other is a 400, so a
 * request that says "assign" and carries a move is not half-obeyed.
 */
export interface BulkCardCommandRequest {
  card_ids: string[];
  command: BulkCardCommand;
  /**
   * Move is read by "move". Position is where the first card lands; each
   * card after it lands one further on, so the cards keep the order they
   * were sent in.
   */
  move?: MoveCardRequest;
  /**
   * PrincipalID is read by "assign" and "unassign".
   */
  principal_id?: string;
  /**
   * Reason is read by "hold".
   */
  reason?: string;
  /**
   * Tags is read by "add_tags" and "remove_tags".
   */
  tags?: string[];
}
/**
 * BulkCardCommandResult is what happened to one card: the status and body the
 * single-card route answered, unchanged.
 */
export interface BulkCardCommandResult {
  card_id: string;
  status: number /* int */;
  /**
   * Response is the single-card route's own JSON answer — the placement, the
   * assignment, the item, or {"error":…}.
   */
  response: unknown;
}
/**
 * BulkCardCommandResponse reports every card. The request is not one
 * transaction: each card is its own command, exactly as if it had been sent
 * alone, and a card that was refused undoes nothing done to the others.
 */
export interface BulkCardCommandResponse {
  command: BulkCardCommand;
  succeeded: number /* int */;
  failed: number /* int */;
  results: BulkCardCommandResult[];
}

//////////
// source: messaging.go

/**
 * MessageTrigger is one rule: when EventKind happens to a card on BoardID
 * (and the optional filters agree), render MessageTemplate and send it to
 * RecipientUserID through multichat.
 */
export interface MessageTrigger {
  id: string;
  board_id: string;
  name: string;
  /**
   * EventKind is one of MessageTriggerEventKinds.
   */
  event_kind: EventKind;
  /**
   * ToColumnID narrows a card_moved trigger to moves INTO this column. Empty
   * means any column. Only meaningful with card_moved; refused otherwise.
   */
  to_column_id?: string;
  /**
   * PriorityValue narrows the trigger to cards whose rung on the board's
   * priority ladder has this value (the rung's id — labels are renameable).
   * Nil means any priority, including unranked. The rung's label is carried
   * on the wire as priority_label for display only.
   */
  priority_value?: number /* int */;
  priority_label?: string;
  /**
   * RecipientUserID is multichat's id for the person: the bridge puppet id,
   * e.g. @whatsapp_15551234567:chat.kayushkin.com, from multichat's
   * GET /api/contacts/unified. RecipientDisplayName is for display only and
   * is never read back to find the person.
   */
  recipient_user_id: string;
  recipient_display_name?: string;
  /**
   * MessageTemplate is a Go text/template over MessageTemplateFields.
   */
  message_template: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * MessageTemplateFields is what a trigger's template may reference.
 */
export interface MessageTemplateFields {
  CardID: string;
  Title: string;
  BoardName: string;
  ColumnName: string; // the column the card is in after the action
  FromColumnName: string; // card_moved only
  PriorityLabel: string; // "" when unranked or the board has no ladder
  EventKind: string;
  Actor: string;
  Summary: string;
  AssigneeIDs: string[]; // principal ids
  OccurredAt: string;
}
/**
 * MessageTriggerOptions is what GET /api/message-trigger-options serves: the
 * vocabularies a trigger editor needs and whether delivery is configured on
 * this kanban-store at all, so a UI never hardcodes an event kind or a
 * template field.
 */
export interface MessageTriggerOptions {
  event_kinds: EventKind[];
  column_filter_event_kinds: EventKind[];
  template_fields: string[];
  delivery_configured: boolean;
}
/**
 * UpsertMessageTriggerRequest is the body of POST and PATCH. Every field is a
 * pointer so PATCH can tell "not sent" from "cleared"; POST fills the
 * required ones or is refused.
 */
export interface UpsertMessageTriggerRequest {
  name?: string;
  event_kind?: EventKind;
  to_column_id?: string;
  priority_value?: number /* int */;
  clear_priority?: boolean;
  recipient_user_id?: string;
  recipient_display_name?: string;
  message_template?: string;
  enabled?: boolean;
}
/**
 * MessageDeliveryStatus is what became of one trigger firing on one event.
 */
export type MessageDeliveryStatus = string;
/**
 * DeliveryPending: claimed and handed to multichat, no answer recorded yet.
 * A row left here means kanban-store stopped mid-send; whether the message
 * went out is unknown, and the row says exactly that.
 */
export const DeliveryPending: MessageDeliveryStatus = "pending";
/**
 * DeliverySent: multichat accepted it; RoomID and MatrixEventID say where.
 */
export const DeliverySent: MessageDeliveryStatus = "sent";
/**
 * DeliveryFailed: rendering or multichat failed; Error says why.
 */
export const DeliveryFailed: MessageDeliveryStatus = "failed";
/**
 * DeliveryNotConfigured: the trigger matched and rendered but this
 * kanban-store has no MULTICHAT_URL, so nothing was sent. The row exists
 * so a trigger set up before the wiring is visibly firing into nothing
 * rather than silently doing nothing.
 */
export const DeliveryNotConfigured: MessageDeliveryStatus = "not_configured";
/**
 * MessageDelivery is the audit row for one trigger on one event. The pair is
 * unique: an event is delivered at most once per trigger, however many times
 * the dispatcher sees it.
 */
export interface MessageDelivery {
  id: string;
  trigger_id: string;
  board_id: string;
  event_id: string;
  card_id: string;
  recipient_user_id: string;
  rendered_message: string;
  status: MessageDeliveryStatus;
  error?: string;
  room_id?: string;
  matrix_event_id?: string;
  created_at: string;
}

//////////
// source: model.go

/**
 * Board is a kanban board. Each board defines its own ordered set of columns.
 * Cards (which live in noteboard) attach to a board via Placement rows.
 */
export interface Board {
  id: string;
  name: string;
  description: string;
  archived: boolean;
  /**
   * BusinessHours is the board's working week. Absent means the board reports
   * wall-clock time only; it is never defaulted, because a guessed zone produces
   * business figures nobody can check.
   */
  business_hours?: BusinessHours;
  /**
   * DefaultPrincipalID is principal-store's id for whoever a card on this
   * board belongs to until someone says otherwise. kanban-store applies it
   * itself, at the moment a card is created on or attached to the board, and
   * only when the card has no assignee yet — an assignment a person made is
   * never overwritten by a default. Empty means cards arrive unassigned.
   */
  default_principal_id?: string;
  /**
   * DefaultAgentID is agent-store's numeric id (as llm-bridge-server's GET
   * /agents lists it, never the renameable slug) for the agent a dispatcher
   * spawns to work a card from this board. kanban-store stores and checks it;
   * the dispatcher binaries read it. Empty means the dispatcher has no
   * board-level answer and must refuse rather than guess.
   */
  default_agent_id?: string;
  /**
   * DefaultInstanceID is the llm-bridge-server harness instance that hosts
   * sessions spawned for this board's cards. Same ownership as DefaultAgentID.
   */
  default_instance_id?: string;
  /**
   * DefaultBundleID is bundle-store's numeric id for the session bundle
   * (skills and tools) a dispatcher spawns with for this board's cards.
   * Stored and checked here; the dispatcher sends it as bundle_id on
   * llm-bridge-server's POST /sessions, which resolves and provisions it.
   */
  default_bundle_id?: string;
  /**
   * Classifier says how mail becomes cards on this board. Absent means no
   * classifier files onto it. The scheduler still owns WHEN the classifier
   * runs; this is only WHAT it runs with, so the board is the one place the
   * answer lives instead of a flag on a cron job.
   */
  classifier?: ClassifierConfig;
  created_at: string;
  updated_at: string;
}
/**
 * ClassifierConfig is what email-classifier reads off a board before filing
 * mail onto it.
 */
export interface ClassifierConfig {
  /**
   * Vocabulary names one of email-classifier's classification schemes
   * ("personal", "work", …). email-classifier owns the list; kanban-store only
   * keeps the name, and the classifier refuses a board naming one it does not
   * have. `email-classifier -list-vocabularies` prints them.
   */
  vocabulary: string;
  /**
   * MailAccountIDs are mailstack's account ids (GET /api/accounts → id) the
   * classifier reads for this board. Explicit, never "every account": a
   * mailbox added later must be pointed at a board on purpose, not swept onto
   * whichever board says "all". Checked by the classifier at run time, since
   * mailstack is behind a token this store does not hold.
   */
  mail_account_ids: string[];
  /**
   * HoldNewCards creates every card parked, so an unattended worker
   * discovering noteboard todos does not pick it up before the pipeline that
   * owns the card releases it.
   */
  hold_new_cards: boolean;
}
export interface CreateBoardRequest {
  name: string;
  description?: string;
}
export interface UpdateBoardRequest {
  name?: string;
  description?: string;
  archived?: boolean;
  /**
   * BusinessHours replaces the board's working week. Sending an object with an
   * empty tzid clears it; omitting the field leaves it alone.
   */
  business_hours?: BusinessHours;
  /**
   * The three default ids: a present empty string clears the field, omitting
   * it leaves it alone. The API checks a non-empty value with its owner
   * (principal-store, llm-bridge-server) before anything is written.
   */
  default_principal_id?: string;
  default_agent_id?: string;
  default_instance_id?: string;
  default_bundle_id?: string;
  /**
   * Classifier replaces the board's classifier config. Sending an empty
   * object clears it; omitting the field leaves it alone.
   */
  classifier?: ClassifierConfig;
}
/**
 * Column belongs to a Board. Position is a float so reorders are cheap
 * (insert between two columns by averaging their positions). AutoStatus, when
 * set, causes a card move into this column to PATCH the noteboard item's
 * status to that value.
 */
export interface Column {
  id: string;
  board_id: string;
  name: string;
  position: number /* float64 */;
  color: string;
  wip_limit?: number /* int */;
  auto_status?: string;
  /**
   * BudgetClockState is what landing in this column means for the budget clock:
   * "In Progress" runs it, "Blocked" pauses it, "Done" stops it. Absent means a
   * move here says nothing about the clock and leaves it as it was — which is the
   * honest default for a column nobody has classified.
   */
  budget_clock_state?: ClockState;
  /**
   * LifecycleState is what sitting in this column means for a ticket: new,
   * open, waiting on the requester, resolved or closed. Absent means this
   * column has not been classified, and a ticket here reports no state
   * rather than a guessed one — see model/ticket.go.
   */
  lifecycle_state?: TicketLifecycleState;
  created_at: string;
  updated_at: string;
}
export interface CreateColumnRequest {
  name: string;
  position?: number /* float64 */;
  color?: string;
  wip_limit?: number /* int */;
  auto_status?: string;
  budget_clock_state?: ClockState;
  /**
   * LifecycleState classifies the column for tickets; see Column.
   */
  lifecycle_state?: string;
}
export interface UpdateColumnRequest {
  name?: string;
  position?: number /* float64 */;
  color?: string;
  wip_limit?: number /* int */;
  auto_status?: string;
  /**
   * BudgetClockState reclassifies the column. An empty string clears it.
   */
  budget_clock_state?: ClockState;
  /**
   * LifecycleState reclassifies the column for tickets. An empty string
   * clears it, which makes every ticket in the column report no state.
   */
  lifecycle_state?: string;
}
/**
 * Placement attaches a noteboard item (the card) to a board+column at a position.
 * Many-to-many: the same card_id can appear in multiple boards.
 */
export interface Placement {
  card_id: string;
  board_id: string;
  column_id: string;
  position: number /* float64 */;
  created_at: string;
  updated_at: string;
}
/**
 * CreateCardRequest is the kanban-side payload. Title is required; remaining
 * fields pass through to noteboard. ColumnID is required so the new card lands
 * somewhere on the board.
 */
export interface CreateCardRequest {
  title: string;
  body?: string;
  tags?: string[];
  priority?: number /* int */;
  list_id?: string;
  due_at?: string;
  column_id: string;
  position?: number /* float64 */;
  /**
   * ParentID makes this card a child of another item. The hold gate and the
   * spend ceiling roll up over this edge, so a sub-card created without it
   * escapes its parent's hold and its parent's spend ceiling.
   */
  parent_id?: string;
  /**
   * Hold creates the card parked — agents cannot pick the work up until a human
   * presses play. Opt-in, for classes of work that should never run unattended.
   */
  hold?: boolean;
  hold_reason?: string;
  /**
   * AutoHoldAtUSD is the spend ceiling: hold this card once its agent sessions
   * have cost this much in total. Nil = no ceiling. Zero is a REAL ceiling, so
   * this is a pointer — a plain float64 would make "no ceiling" and "stop before
   * spending a cent" the same request.
   */
  auto_hold_at_usd?: number /* float64 */;
}
/**
 * AttachCardRequest puts an existing noteboard item onto a board.
 */
export interface AttachCardRequest {
  column_id: string;
  position?: number /* float64 */;
}
/**
 * MoveCardRequest moves a card within or across columns of a single board.
 */
export interface MoveCardRequest {
  board_id: string;
  column_id: string;
  position: number /* float64 */;
}
/**
 * CardLink points from a card to an external entity (session, instance,
 * machine, repo, git_repo, skill, tool, …). EntityType is open — kanban-store
 * does not validate that EntityRef exists in the upstream service.
 */
export interface CardLink {
  id: string;
  card_id: string;
  entity_type: string;
  entity_ref: string;
  label: string;
  created_at: string;
}
export interface CreateCardLinkRequest {
  entity_type: string;
  entity_ref: string;
  label?: string;
  /**
   * OccurredAt backdates the ACTION a link records, for the link types that
   * record one. It is the same field, for the same reason, as the one on
   * CreateCardEventRequest: a classifier reads a mailbox on a cadence, so the
   * mail it files arrived before anything here heard about it. Without this,
   * attaching week-old mail reported it as arriving now, and every card built
   * by filing a backlog carried a timeline that began the moment it was filed.
   * It does NOT move the link's own CreatedAt. When the link was recorded and
   * when the thing happened are two different facts, and the event type here
   * already keeps them apart as RecordedAt and OccurredAt.
   * Sending it with a link type that records no action is an error rather than
   * a no-op — see the handler. Silently ignoring it would let a caller believe
   * it had backdated something it had not.
   */
  occurred_at?: string;
  /**
   * ClockState overrides what the arrival means for the budget clock.
   * The link type already implies one — mail arriving is work landing in front
   * of you, so it runs the clock. That is right for a card someone works, and
   * wrong for a bucket: a hundred build digests filed on one No-action card
   * are not a hundred arrivals of work, and letting them run the clock reports
   * a card nobody has ever touched as having consumed weeks of budget.
   * Like OccurredAt, it is refused on a link type that records no action.
   */
  clock_state?: ClockState;
}
/**
 * CardAssignment says a principal is on a card. It is its own fact about the
 * card, not a card link: a link's label is a display name and its uniqueness is
 * per entity ref, and neither is what "assigned" means. PrincipalID is an id
 * minted by principal-store, which owns who a principal is; kanban-store checks
 * it exists there before writing the row and never stores the name.
 * There is no role. Version one answers "who is assigned"; owner versus
 * reviewer is a later question, if it is ever asked.
 */
export interface CardAssignment {
  card_id: string;
  principal_id: string;
  assigned_by: string;
  created_at: string;
}
/**
 * EntityTag is cross-cutting: tag any (entity_type, entity_ref) pair without
 * involving cards or boards. Lets agents tag a session "p0" or a machine "lab".
 */
export interface EntityTag {
  entity_type: string;
  entity_ref: string;
  tag: string;
  created_at: string;
}
export interface CreateEntityTagRequest {
  tag: string;
}
/**
 * BoardView is the assembled response for GET /api/boards/:id/cards.
 * Cards are joined with their noteboard content; columns carry their cards
 * in placement order.
 */
export interface BoardView {
  board: Board;
  columns: ColumnView[];
  orphans?: CardView[];
  /**
   * PriorityLadder is the board's rungs, so a client can label and colour a card
   * without asking a second time. An empty ladder means this board ignores
   * priorities.
   */
  priority_ladder?: PriorityLadder;
}
export interface ColumnView {
  column: Column;
  cards: CardView[];
  /**
   * Total is how many cards the column holds, which is not len(Cards) once a
   * board view has been capped. A client needs both to say "showing 25 of 6,466"
   * rather than quietly presenting a page as the whole column.
   */
  total: number /* int */;
}
/**
 * CardView combines a placement with its noteboard item content (passed
 * through unchanged), links and assignments. Item is `any` so we don't
 * redefine noteboard's Item shape here.
 */
export interface CardView {
  placement: Placement;
  /**
   * Item is the noteboard item, passed through unchanged; null when the item
   * was hard-deleted out from under kanban-store (see BoardView.Orphans).
   */
  item: NoteboardItem | null;
  links?: CardLink[];
  assignments?: CardAssignment[];
  /**
   * Ticket is present when this card came from outside; absent on an
   * ordinary card. The lifecycle is not repeated here — it is the column
   * this very placement names, which the reader already has.
   */
  ticket?: Ticket;
  /**
   * AutoStatusApplied and AutoStatusError report the second write a card
   * creation makes: when the destination column carries auto_status, the
   * noteboard item is PATCHed to match. That write can fail on its own after
   * the card already exists, and an unreported failure leaves the item reading
   * "open" in a Done column — which is both the state auto_status exists to
   * prevent and indistinguishable from a column that has no auto_status at
   * all. Same field names moveCard answers with, because it is the same event.
   */
  auto_status_applied?: string;
  auto_status_error?: string;
  /**
   * Time is the card's clock as the board sees it: how long it has been alive,
   * how much of that counted as workable, and how that sits against the limit
   * its priority sets. Computed from the card's events on every read, never
   * stored.
   */
  time?: CardTimeSummary;
}
/**
 * CallerAccess is what the caller of this very request may do on one board or
 * one card, so a client can offer only the commands the store would accept
 * instead of learning each refusal by trying.
 * Relations is every grant-store board relation that holds for the caller,
 * weakest first, with kanban-store's inclusion rule already applied: a caller
 * who may edit is listed as can_view and can_edit. A client asks whether the
 * relation it needs is in the list and never learns the ordering.
 */
export interface CallerAccess {
  /**
   * PrincipalID is absent when an internal service sent the service token.
   */
  principal_id?: string;
  /**
   * Unrestricted is true for the service token and for an administrator:
   * every relation holds, whatever was granted.
   */
  unrestricted: boolean;
  relations: string[];
}
/**
 * CardDetail is GET /api/cards/{id}: one card read through the gate. A card's
 * content lives in noteboard, which has no callers' rules of its own, so this
 * is the only read of a card's body that checks who is asking.
 */
export interface CardDetail {
  card_id: string;
  /**
   * Item is the noteboard item, passed through unchanged; null when the item
   * was deleted out from under its placements.
   */
  item: NoteboardItem | null;
  /**
   * Placements are the boards the caller can view, not every board the card
   * sits on: a board the caller cannot see is not named to it.
   */
  placements: (Placement | undefined)[];
  links?: CardLink[];
  assignments?: CardAssignment[];
  ticket?: TicketView;
  /**
   * Access is what the caller may do to this card. Editing needs can_edit on
   * every board the card sits on, seen or not, so a card on a board the
   * caller cannot view is can_view here however much it holds elsewhere.
   */
  access: CallerAccess;
}
/**
 * EntityCardView is one row of GET /api/entities/{type}/{ref}/cards: a card
 * that links the entity, with its noteboard item passed through unchanged.
 * Item is null when the item was hard-deleted out from under kanban-store, so
 * a caller can spot orphans.
 */
export interface EntityCardView {
  card_id: string;
  item: NoteboardItem | null;
}
export interface EntityTypeInfo {
  type: string;
  service?: string;
  search?: string;
  /**
   * Get is the owning service's fetch-one-by-id route, relative to the
   * service root, with "{id}" marking where the id goes (e.g.
   * "/api/items/{id}"). Empty means the service has no by-id lookup for this
   * type, so a reference resolver cannot probe it.
   */
  get?: string;
  /**
   * IDPatterns are case-insensitive regular expressions describing what this
   * type's ids look like, matched against the WHOLE candidate id (resolvers
   * anchor them). A reference resolver probes an id against every type whose
   * pattern matches. Empty means ids of this type have no recognizable shape
   * and are never probed.
   */
  id_patterns?: string[];
}
export interface TagCount {
  tag: string;
  count: number /* int */;
}

//////////
// source: tag_rules.go

/**
 * DefaultField names one of the four defaults a board or a tag rule may set.
 * Its value is the JSON key both carry, so a resolution is keyed the way the
 * board is written.
 */
export type DefaultField = string;
export const DefaultFieldPrincipal: DefaultField = "default_principal_id";
export const DefaultFieldAgent: DefaultField = "default_agent_id";
export const DefaultFieldInstance: DefaultField = "default_instance_id";
export const DefaultFieldBundle: DefaultField = "default_bundle_id";
/**
 * BoardTagRule is one stored rule. Position is its place in the board's
 * order, 0 first; a lower position wins.
 */
export interface BoardTagRule {
  id: string;
  board_id: string;
  position: number /* int */;
  tags: string[];
  default_principal_id?: string;
  default_agent_id?: string;
  default_instance_id?: string;
  default_bundle_id?: string;
  created_at: string;
  updated_at: string;
}
/**
 * BoardTagRules is a board's whole ordered list.
 */
export interface BoardTagRules {
  board_id: string;
  rules: BoardTagRule[];
}
/**
 * BoardTagRuleInput is one rule as PUT sends it. ID, when given, keeps an
 * existing rule's id and created_at; omitted, the store mints one.
 */
export interface BoardTagRuleInput {
  id?: string;
  tags: string[];
  default_principal_id?: string;
  default_agent_id?: string;
  default_instance_id?: string;
  default_bundle_id?: string;
}
/**
 * SetBoardTagRulesRequest replaces a board's rules wholesale, in the order
 * given. Rules only mean anything relative to each other, so, like the
 * priority ladder, there is no endpoint for editing one rule.
 */
export interface SetBoardTagRulesRequest {
  rules: BoardTagRuleInput[];
}
/**
 * Where a resolved default came from.
 */
export const DefaultSourceBoard = "board";
/**
 * Where a resolved default came from.
 */
export const DefaultSourceTagRule = "tag_rule";
/**
 * DefaultSource says which setting a resolved default was read from. For a tag
 * rule it carries the rule's id, and its tags and position for display.
 */
export interface DefaultSource {
  kind: string;
  rule_id?: string;
  rule_tags?: string[];
  rule_position?: number /* int */;
}
/**
 * EffectiveDefault is one resolved default and where it came from.
 */
export interface EffectiveDefault {
  value: string;
  source: DefaultSource;
}
/**
 * EffectiveDefaults is what a card with these tags gets on this board. A field
 * absent from Defaults has no value anywhere: no matching rule sets it and the
 * board does not either.
 */
export interface EffectiveDefaults {
  board_id: string;
  card_id?: string;
  tags: string[];
  matched_rule_ids: string[];
  defaults: { [key: DefaultField]: EffectiveDefault};
}

//////////
// source: ticket.go

/**
 * TicketChannel is how a ticket reached us.
 */
export type TicketChannel = string;
export const TicketChannelEmail: TicketChannel = "email";
export const TicketChannelPortal: TicketChannel = "portal";
export const TicketChannelChat: TicketChannel = "chat";
export const TicketChannelPhone: TicketChannel = "phone";
/**
 * TicketChannelAgent is a ticket an agent raised on someone's behalf.
 */
export const TicketChannelAgent: TicketChannel = "agent";
/**
 * TicketLifecycleState is where a ticket stands. It is a property of a
 * **column**, not of the ticket: classify the columns of a board once, and
 * every card in them reports its state from where it sits.
 */
export type TicketLifecycleState = string;
/**
 * TicketLifecycleNew — arrived, nobody has picked it up.
 */
export const TicketLifecycleNew: TicketLifecycleState = "new";
/**
 * TicketLifecycleOpen — someone here is working on it.
 */
export const TicketLifecycleOpen: TicketLifecycleState = "open";
/**
 * TicketLifecycleWaitingOnRequester — we answered; the ball is theirs.
 */
export const TicketLifecycleWaitingOnRequester: TicketLifecycleState = "waiting_on_requester";
/**
 * TicketLifecycleResolved — we believe it is done; the requester has not
 * said otherwise yet.
 */
export const TicketLifecycleResolved: TicketLifecycleState = "resolved";
/**
 * TicketLifecycleClosed — over, and not coming back without a new ticket.
 */
export const TicketLifecycleClosed: TicketLifecycleState = "closed";
/**
 * Ticket is the stored row: the two facts a card cannot hold.
 */
export interface Ticket {
  card_id: string;
  /**
   * RequesterPrincipalID is a principal-store **contact** — the outside
   * person who asked. Checked with principal-store on write, and stored as
   * an id: an address is a name, and one person writes from three of them.
   */
  requester_principal_id: string;
  channel: TicketChannel;
  created_at: string;
  updated_at: string;
}
/**
 * TicketPlacementState is the lifecycle a ticket has **on one board**, read
 * from the column the card sits in there.
 */
export interface TicketPlacementState {
  board_id: string;
  column_id: string;
  column_name: string;
  /**
   * LifecycleState is absent when that column has not been classified. That
   * is the honest answer for a board whose columns nobody has mapped: it is
   * not "new", and saying "new" would start an SLA clock on a guess.
   */
  lifecycle_state?: TicketLifecycleState;
}
/**
 * TicketView is what a reader gets: the row, the requester's name for display
 * only, and one lifecycle per board the card sits on.
 * Plural on purpose. A card can be on two boards at once — the mail board it
 * arrived on and the team board it was pulled onto — and those columns can
 * disagree. Answering every placement lets the reader say which board it is
 * asking about; answering one would be this store picking, and picking wrong
 * is indistinguishable from picking right until someone is paged.
 */
export interface TicketView {
  ticket?: Ticket;
  /**
   * RequesterDisplayName is a copy of principal-store's name, for rendering
   * a board without a second fetch per card. Nothing joins on it: the id
   * above is the only handle, and this string is stale the moment the
   * contact is renamed.
   */
  requester_display_name?: string;
  states: TicketPlacementState[];
}
/**
 * TicketWriteRequest is the body of PUT /api/cards/{id}/ticket.
 */
export interface TicketWriteRequest {
  requester_principal_id: string;
  channel: string;
}

//////////
// source: time_entry.go

/**
 * EventTimeLogged is a person recording time they spent on a card: "45 minutes
 * on the phone with the carrier". It is an event like any other and sits on the
 * timeline with the moves and the notes.
 * It has no kind-level clock state, like an assignment: saying how long
 * something took says nothing about whether the work is runnable now, so the
 * event carries the state the card was already in. And it happens when it is
 * LOGGED, not when the work was done — the clock is the walk of the events in
 * order, and an entry backdated to yesterday would split an interval that was
 * already accounted for. When the work was done is TimeLoggedEventDetail.WorkedAt.
 * It is written only through POST /api/cards/{id}/time-entries, never through
 * /events, because an entry may replace another and that has rules.
 */
export const EventTimeLogged: EventKind = "time_logged";
/**
 * MaxTimeEntrySeconds bounds one entry at 31 days. It exists to catch a unit
 * mistake — milliseconds sent as seconds — not to say how long work may take.
 */
export const MaxTimeEntrySeconds = 31 * 24 * 3600;
/**
 * TimeLoggedEventDetail is the detail of a time_logged event.
 */
export interface TimeLoggedEventDetail {
  /**
   * Seconds is the time spent. Zero only on an entry that replaces another:
   * that is how an entry is withdrawn.
   */
  seconds: number /* int64 */;
  /**
   * WorkerPrincipalID is who did the work, a principal-store human. It is not
   * always the event's actor: a lead may log time for someone on their team.
   */
  worker_principal_id: string;
  /**
   * WorkedAt is when the work was done, when the person logging it said so.
   */
  worked_at?: string;
}
/**
 * CreateTimeEntryRequest is POST /api/cards/{id}/time-entries.
 */
export interface CreateTimeEntryRequest {
  seconds: number /* int64 */;
  /**
   * WorkerPrincipalID defaults to the calling principal. A caller with no
   * principal — an internal service — must name one.
   */
  worker_principal_id?: string;
  worked_at?: string;
  /**
   * Summary says what the time went on. It is the event's summary.
   */
  summary?: string;
  board_id?: string;
  /**
   * SupersedesEventID makes this entry a correction of another: the entry it
   * names stops counting and this one counts in its place. Nothing is
   * rewritten — the old entry stays on the timeline exactly as it was logged,
   * and is inactive because this one points at it. An entry can be replaced
   * once; correcting a correction names the newest one.
   */
  supersedes_event_id?: string;
}
/**
 * TimeEntry is one time_logged event read as what it is.
 */
export interface TimeEntry {
  event_id: string;
  card_id: string;
  board_id?: string;
  seconds: number /* int64 */;
  worker_principal_id: string;
  worked_at?: string;
  summary?: string;
  /**
   * LoggedBy is the event's actor and LoggedAt its occurred_at.
   */
  logged_by?: string;
  logged_at: string;
  /**
   * SupersedesEventID is the entry this one replaced; SupersededByEventID is
   * the entry that replaced this one. Follow either to read an entry's history.
   */
  supersedes_event_id?: string;
  superseded_by_event_id?: string;
  /**
   * Active is false once another entry has replaced this one. Only active
   * entries count.
   */
  active: boolean;
}
/**
 * CardTimeEntries is GET /api/cards/{id}/time-entries.
 */
export interface CardTimeEntries {
  card_id: string;
  /**
   * ActiveSeconds is the sum over active entries, whatever filter was asked
   * for: it is the card's logged time.
   */
  active_seconds: number /* int64 */;
  entries: TimeEntry[];
}

//////////
// source: timesummary.go

/**
 * TimeSegment is the stretch between one event and the next, carrying the clock
 * state the earlier event put the card into.
 */
export interface TimeSegment {
  event_id: string;
  clock_state: ClockState;
  from: string;
  to: string;
  seconds: number /* float64 */;
  /**
   * Open marks the segment that is still running: it ends at the moment the
   * figures were computed, not at an event, so it grows until something happens.
   */
  open: boolean;
}
/**
 * TimelineEntry is one event with the time either side of it: how long since the
 * previous action, and how long the card then spent in the state this action put
 * it in.
 */
export interface TimelineEntry {
  event: CardEvent;
  note?: CardNote;
  seconds_since_previous_event: number /* float64 */;
  segment_seconds: number /* float64 */;
  segment_open: boolean;
  counts_against_budget: boolean;
  clock_state: ClockState;
  /**
   * SupersededByEventID is set on an event another one has replaced — a time
   * entry that was corrected. It stays on the timeline as it was logged, and
   * this is what says it no longer counts.
   */
  superseded_by_event_id?: string;
}
/**
 * CardTimeSummary is the card's time, answered three ways.
 */
export interface CardTimeSummary {
  as_of: string;
  /**
   * ClockState is where the card stands right now — the state its most recent
   * action left it in.
   */
  clock_state: ClockState;
  first_event_at?: string;
  last_event_at?: string;
  event_count: number /* int */;
  /**
   * ElapsedSeconds is wall clock from the first action to now, or to the action
   * that stopped the card. Your 25.5 hours.
   */
  elapsed_seconds: number /* float64 */;
  /**
   * BudgetClockSeconds is the part of that the work was actually available to be
   * worked on. Your 1.5 hours. This is what the limit is measured against.
   */
  budget_clock_seconds: number /* float64 */;
  /**
   * WaitingSeconds is the rest: time the ball was with someone else. Your 24.
   */
  waiting_seconds: number /* float64 */;
  /**
   * LoggedSeconds is the time people have recorded by hand on the card: the
   * sum of its active time entries. It is a different thing from the three
   * figures above, which are read off the clock — those say how long the card
   * took, this says how much work somebody says they did. An entry that has
   * been replaced does not count; its replacement does.
   */
  logged_seconds: number /* int64 */;
  /**
   * BusinessHoursElapsedSeconds and BusinessHoursBudgetClockSeconds repeat the
   * two figures above counting only the board's working week. Both are absent
   * when the board has no business hours configured — an unconfigured board
   * reports nothing here rather than a guessed nine-to-five.
   */
  business_hours_elapsed_seconds?: number /* float64 */;
  business_hours_budget_clock_seconds?: number /* float64 */;
  /**
   * The rung this card's priority sits on, if its board has a ladder and the
   * card is ranked. PriorityLabel is what the board calls it — "P0".
   */
  priority_value?: number /* int */;
  priority_label?: string;
  /**
   * BudgetSeconds is the limit that rung sets. Absent means no limit applies,
   * either because the board ignores priorities, the card is unranked, or the
   * rung is named but untimed — and then Remaining and OverBudget are absent too,
   * because there is nothing to be over.
   */
  budget_seconds?: number /* int */;
  budget_remaining_seconds?: number /* float64 */;
  over_budget?: boolean;
  segments?: TimeSegment[];
}
/**
 * CardTimeline is the answer to "what happened to this card, in what order, and
 * how long did each step take".
 */
export interface CardTimeline {
  card_id: string;
  board_id?: string;
  summary: CardTimeSummary;
  entries: TimelineEntry[];
  notes: CardNote[];
  priority_level?: BoardPriorityLevel;
}
